### ISSUE TITLE
Missing gnu tools in the install specification

### ISSUE THREAD

**Issue by CarlsenSmart** [Mortal/rtmpdump-lifesize#3]
Hey :)

Just wanna say that the `make` command didn't work for me before I also installed some gnu tools with this command:

`sudo apt-get install libgnutls28-dev`

After this everything worked.

**Comment by Mortal** [comment]
Thanks for the suggestion - that should be added. Can you please send a pull request where you add it to the README?

**Comment by CarlsenSmart** [comment]
Yeps :) Have made one now.

**Comment by Mortal** [comment]
Thanks! By doing the work, you made sure the work was done! If you had waited for me to do it, well...
